{% set name = "python-javabridge" %}
{% set version = "4.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-javabridge-{{ version }}.tar.gz
  sha256: 27ab04b2ae0e5f44d07854e9103dd125374d1cd9f797a2073284670de1027124

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29.16
    - numpy >=1.18.2
    - pip
    - python
    - openjdk
  run:
    - numpy >=1.18.2
    - python
    - {{ pin_compatible('numpy') }}
    - openjdk
  run_constrained:
    - javabridge ==9999999999

test:
  imports:
    - javabridge
    - javabridge.tests
  requires:
    - nose
    - openjdk

about:
  home: http://github.com/CellProfiler/python-javabridge/
  summary: Python wrapper for the Java Native Interface
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raivivek
