{% set name = "python-javabridge" %}
{% set version = "4.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-javabridge-{{ version }}.tar.gz
  sha256: 3fee0c235efcfe866f95695fdc0b6289eab2371043b32ff4ca6feff098de59c5

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=0.29.16
    - numpy  >=1.20.1
    - pip
    - python  >3.6
    - openjdk
  run:
    - numpy  >=1.20.1
    - python  >3.6
    - openjdk
  run_constrained:
    - javabridge ==9999999999

test:
  imports:
    - javabridge
    - javabridge.tests
  requires:
    - nose
    - openjdk

about:
  home: http://github.com/CellProfiler/python-javabridge/
  summary: Python wrapper for the Java Native Interface
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raivivek
